# Generated by Django 4.0.2 on 2022-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='name')),
                ('user_last_name', models.CharField(max_length=20, verbose_name='lastName')),
                ('user_email', models.EmailField(max_length=30, verbose_name='email')),
                ('user_password', models.CharField(max_length=15, verbose_name='password')),
            ],
        ),
    ]
